### ISSUE TITLE
Exit function fails when using exit function a second time after reconnecting

### ISSUE THREAD

**Issue by ECDOEG** [Red-M/RedExpect#1]
I have tried using the same object to connect, run a command, and then disconnect, and then reconnect again and repeat the process. This almost works as expected. I can reconnect using the same object, and successfully run a command, but I cannot then use the exit function to close the connection. I receive the following error:
```
File "C:\Users\...\venv\lib\site-packages\redssh\redssh.py", line 588, in exit
    if not self._ssh_keepalive_thread==None:
AttributeError: 'RedExpect' object has no attribute '_ssh_keepalive_thread'
```

I can still continue to run commands with the same object, but I cannot find a way to simply close the connection entirely, after a I reconnect.

The closest work around I have found is, after using exit the first time, I delete the object, but this is inconvenient to me to have to recreate the object over again.

**Comment by Red-M** [comment]
Hey,

Sorry about the late reply but the objects are not meant to be reused like that.
Its not a hard patch to allow this but wasn't part of the original design, still, I'll take a look at this in depth and if this doesn't cause issues like memory leaks.

**Comment by Red-M** [comment]
This should be fixed in RedSSH now.
You'll need to update RedSSH to allow RedExpect to take the changes from upstream.

**Comment by Red-M** [comment]
Please re-open this issue if there is further issues or questions arising from this subject matter.
