### ISSUE TITLE
command output not returned immediately

### ISSUE THREAD

**Issue by James-Hudson3010** [Red-M/RedExpect#2]
I have a script that looks like:

```
import redexpect
expect = redexpect.RedExpect()
expect.connect( ... )
output = expect.command( 'mount', remove_newline = True )
print( output )
print( "---" )
output = expect.command( 'ls -la', remove_newline = True )
print( output )
expect.exit()
```

The output from the 'mount' command is not returned until the output variable is assigned with the 'ls -la' command.

There is probably something I am misunderstanding about how this should work.

**Comment by Red-M** [comment]
Instead of `connect()` you need to use `login()`, otherwise a few variables are never set for RedExpect to work.

I need to figure out some way to get the documentation to put a warning in for `connect()` in RedExpect since that function is inherited from RedSSH.

**Comment by James-Hudson3010** [comment]
Confirmed. That worked.

**Comment by Red-M** [comment]
cb64e45de1400feec29728ad0b9bb7fd43ce1fca should fix this very issue.

**Comment by James-Hudson3010** [comment]
excellent. thank you. I am sure many will find this useful.
