### ISSUE TITLE
redssh.exceptions.AuthenticationFailedException

### ISSUE THREAD

**Issue by binooetomo** [Red-M/RedExpect#4]
dear all.
I have a target host that I can ssh to it without password.
But I fail login using redExpect :
```

(coba2) debian@debian-mon:~/coba2$ ssh root@10.90.200.55 -p 3322
Last login: Fri Sep 18 10:23:25 2020 from 10.90.200.57
[root@candibinangun ~]# exit
logout
Connection to 10.90.200.55 closed.
(coba2) debian@debian-mon:~/coba2$ python
Python 3.8.5 (default, Aug 28 2020, 06:44:01) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import redexpect
>>> 
>>> sshObj = redexpect.RedExpect()
>>> sshObj.login('10.90.200.55', port=3322, username='root', timeout=1.5)
WARN: ('Host %s not found in known hosts collection', b'10.90.200.55')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/debian/.local/share/virtualenvs/coba2-gQE_YhKQ/lib/python3.8/site-packages/redexpect/redexpect.py", line 75, in login
    self.connect(*args,**kwargs)
  File "/home/debian/.local/share/virtualenvs/coba2-gQE_YhKQ/lib/python3.8/site-packages/redssh/redssh.py", line 358, in connect
    self._auth(username,password,allow_agent,host_based,key_filepath,passphrase,look_for_keys)
  File "/home/debian/.local/share/virtualenvs/coba2-gQE_YhKQ/lib/python3.8/site-packages/redssh/redssh.py", line 222, in _auth
    raise(exceptions.AuthenticationFailedException(list(set(auth_types_tried))))
redssh.exceptions.AuthenticationFailedException: Failed to authenticated to remote server via: 

```

Yes I read the docs, but I can't understand which part of it to fix my problem

Sincerely
-bino-

**Comment by Red-M** [comment]
Hi,

Thanks for the detailed bug report, what you've come across is actually a bug in [`redssh.RedSSH.connect()`](https://redssh.readthedocs.io/en/latest/redssh.html#redssh.RedSSH.connect) which allowed you to try to connect to a remote server without offering anything for the client to authenticate with.
I've released a new version to pypi with the fixed behaviour to not allow you to do that.
All you need to do is pass a `password='<password>'` , `allow_agent=True` to allow for using an SSH key agent or a `key_filepath='<path_to_key_file>'` with an optional `passphrase='<key_passhrase>'` to connect.

Please update `redssh` to at least `2.2.4-1`

Please re-open this if this is still causing an issue after providing an authentication argument.
